"""Preset audio catalog for Floppy seed/pregen.

Source: docs/preset_audio_catalog_v0.md + real audio pack (Floppy_audio_v3).
provider_strategy: "minimax" for TTS-readable, "real" for imported real audio.
is_real: True for white_noise/music backed by real mp3 files under real/.
"""

from __future__ import annotations

AUDIO_CATALOG: list[dict] = [
    # =========================================================================
    # WHITE NOISE (14) — real public-domain field recordings (real/white_noise/)
    # =========================================================================
    {"title": "夜雨轻敲", "audio_type": "white_noise", "request_text": "雨打帐篷帆布的轻柔夜雨白噪音，无雷声，安静入睡", "object_key": "real/white_noise/01.mp3", "duration_sec": 1200, "tags": ["rain", "ambient", "nature", "low_stimulation", "no_voice"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["environmental_sleep", "anxiety_relief"], "quality_score": 0.86, "is_real": True, "voice_style": None},
    {"title": "夜海浪涌", "audio_type": "white_noise", "request_text": "夜晚海滩温柔海浪声白噪音，无海鸥，平稳持续", "object_key": "real/white_noise/02.mp3", "duration_sec": 1200, "tags": ["ocean", "ambient", "nature", "low_stimulation", "no_voice"], "mood_tags": ["calm"], "user_segment_tags": ["environmental_sleep", "balanced_sleep"], "quality_score": 0.85, "is_real": True, "voice_style": None},
    {"title": "山涧瀑流", "audio_type": "white_noise", "request_text": "低音山间溪流瀑布自然白噪音，清澈平静", "object_key": "real/white_noise/03.mp3", "duration_sec": 1200, "tags": ["ambient", "nature", "low_stimulation", "no_voice"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["environmental_sleep", "quick_sleep"], "quality_score": 0.84, "is_real": True, "voice_style": None},
    {"title": "壁炉火焰", "audio_type": "white_noise", "request_text": "壁炉柴火噼啪燃烧声，温暖安心的白噪音", "object_key": "real/white_noise/04.mp3", "duration_sec": 1200, "tags": ["ambient", "low_stimulation", "no_voice"], "mood_tags": ["safe", "calm"], "user_segment_tags": ["environmental_sleep", "companionship"], "quality_score": 0.84, "is_real": True, "voice_style": None},
    {"title": "南美雨林", "audio_type": "white_noise", "request_text": "南美雨林河流鸟鸣昆虫的白昼森林自然音", "object_key": "real/white_noise/05.mp3", "duration_sec": 1200, "tags": ["nature", "ambient", "low_stimulation", "no_voice"], "mood_tags": ["calm"], "user_segment_tags": ["environmental_sleep", "anxiety_relief"], "quality_score": 0.83, "is_real": True, "voice_style": None},
    {"title": "轻柔风扇", "audio_type": "white_noise", "request_text": "温柔摆头风扇的持续低响白噪音，单调助眠", "object_key": "real/white_noise/06.mp3", "duration_sec": 1200, "tags": ["ambient", "low_stimulation", "no_voice"], "mood_tags": ["calm"], "user_segment_tags": ["environmental_sleep", "quick_sleep"], "quality_score": 0.82, "is_real": True, "voice_style": None},
    {"title": "雨夜微雷", "audio_type": "white_noise", "request_text": "中等小雨配低沉远雷的阴天雨声白噪音", "object_key": "real/white_noise/12.mp3", "duration_sec": 1200, "tags": ["rain", "ambient", "nature", "low_stimulation", "no_voice"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["environmental_sleep", "anxiety_relief"], "quality_score": 0.84, "is_real": True, "voice_style": None},
    {"title": "雨打树叶", "audio_type": "white_noise", "request_text": "最轻柔的细雨滴落树梢声，无雷，安静雨声", "object_key": "real/white_noise/13.mp3", "duration_sec": 1200, "tags": ["rain", "ambient", "nature", "low_stimulation", "no_voice"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["environmental_sleep", "quick_sleep"], "quality_score": 0.85, "is_real": True, "voice_style": None},
    {"title": "夏夜虫鸣", "audio_type": "white_noise", "request_text": "夏夜蟋蟀虫鸣配河流夜枭的林间夜声白噪音", "object_key": "real/white_noise/14.mp3", "duration_sec": 1200, "tags": ["nature", "ambient", "low_stimulation", "no_voice"], "mood_tags": ["calm"], "user_segment_tags": ["environmental_sleep", "anxiety_relief"], "quality_score": 0.82, "is_real": True, "voice_style": None},
    {"title": "蛙鸣夜沼", "audio_type": "white_noise", "request_text": "夜晚沼泽蛙声配雨滴的自然白噪音", "object_key": "real/white_noise/15.mp3", "duration_sec": 1200, "tags": ["nature", "ambient", "rain", "low_stimulation", "no_voice"], "mood_tags": ["calm"], "user_segment_tags": ["environmental_sleep", "balanced_sleep"], "quality_score": 0.81, "is_real": True, "voice_style": None},
    {"title": "篝火夜林", "audio_type": "white_noise", "request_text": "噼啪篝火配蟋蟀和雨声的夜晚森林白噪音", "object_key": "real/white_noise/16.mp3", "duration_sec": 1200, "tags": ["nature", "ambient", "low_stimulation", "no_voice"], "mood_tags": ["safe", "calm"], "user_segment_tags": ["environmental_sleep", "companionship"], "quality_score": 0.83, "is_real": True, "voice_style": None},
    {"title": "雪夜微风", "audio_type": "white_noise", "request_text": "轻雪配微风的黄昏入夜森林白噪音", "object_key": "real/white_noise/17.mp3", "duration_sec": 1200, "tags": ["nature", "ambient", "low_stimulation", "no_voice"], "mood_tags": ["calm"], "user_segment_tags": ["environmental_sleep", "balanced_sleep"], "quality_score": 0.82, "is_real": True, "voice_style": None},
    {"title": "棕噪低吟", "audio_type": "white_noise", "request_text": "低频棕噪音温柔持续，似引擎或急流的稳定白噪音", "object_key": "real/white_noise/18.mp3", "duration_sec": 1200, "tags": ["ambient", "low_stimulation", "no_voice"], "mood_tags": ["calm"], "user_segment_tags": ["environmental_sleep", "quick_sleep"], "quality_score": 0.81, "is_real": True, "voice_style": None},
    {"title": "海岸雷雨", "audio_type": "white_noise", "request_text": "极低沉雷声配雨和海浪的海滩雷雨白噪音", "object_key": "real/white_noise/19.mp3", "duration_sec": 1200, "tags": ["rain", "ocean", "ambient", "nature", "low_stimulation", "no_voice"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["environmental_sleep", "anxiety_relief"], "quality_score": 0.83, "is_real": True, "voice_style": None},
    # =========================================================================
    # MUSIC (11) — real public-domain / CC0 performances (real/music/)
    # =========================================================================
    {"title": "肖邦钢琴夜曲集", "audio_type": "music", "request_text": "肖邦钢琴前奏曲圆舞曲串联，睡前放松钢琴独奏", "object_key": "real/music/07.mp3", "duration_sec": 1200, "tags": ["ambient", "minimal_voice", "slow_pace", "low_stimulation", "no_voice"], "mood_tags": ["calm"], "user_segment_tags": ["environmental_sleep", "balanced_sleep"], "quality_score": 0.85, "is_real": True, "voice_style": None},
    {"title": "舒伯特钢琴奏鸣曲", "audio_type": "music", "request_text": "舒伯特钢琴奏鸣曲完整乐章，安静抒情钢琴独奏", "object_key": "real/music/08.mp3", "duration_sec": 1105, "tags": ["ambient", "minimal_voice", "slow_pace", "low_stimulation", "no_voice"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["balanced_sleep", "companionship"], "quality_score": 0.84, "is_real": True, "voice_style": None},
    {"title": "德沃夏克美国弦乐四重奏", "audio_type": "music", "request_text": "德沃夏克美国弦乐四重奏，温柔弦乐合奏轻音乐", "object_key": "real/music/09.mp3", "duration_sec": 1200, "tags": ["ambient", "slow_pace", "low_stimulation", "no_voice"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["balanced_sleep", "companionship"], "quality_score": 0.83, "is_real": True, "voice_style": None},
    {"title": "鲍罗丁第一弦乐四重奏", "audio_type": "music", "request_text": "鲍罗丁弦乐四重奏，绵长温柔的弦乐轻音乐", "object_key": "real/music/10.mp3", "duration_sec": 1200, "tags": ["ambient", "slow_pace", "low_stimulation", "no_voice"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["balanced_sleep", "companionship"], "quality_score": 0.82, "is_real": True, "voice_style": None},
    {"title": "小提琴冥想曲与长笛", "audio_type": "music", "request_text": "舒克冥想曲小提琴配莫扎特长笛序曲，抒情助眠轻音乐", "object_key": "real/music/11.mp3", "duration_sec": 1097, "tags": ["ambient", "slow_pace", "low_stimulation", "minimal_voice", "no_voice"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["balanced_sleep", "anxiety_relief"], "quality_score": 0.83, "is_real": True, "voice_style": None},
    {"title": "肖邦夜曲精选", "audio_type": "music", "request_text": "肖邦夜曲串联，最适合入睡的钢琴独奏轻音乐", "object_key": "real/music/20.mp3", "duration_sec": 1200, "tags": ["ambient", "minimal_voice", "slow_pace", "low_stimulation", "no_voice"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["balanced_sleep", "anxiety_relief"], "quality_score": 0.86, "is_real": True, "voice_style": None},
    {"title": "巴赫哥德堡变奏曲", "audio_type": "music", "request_text": "巴赫哥德堡变奏曲咏叹调，宁静钢琴独奏轻音乐", "object_key": "real/music/21.mp3", "duration_sec": 1200, "tags": ["ambient", "minimal_voice", "slow_pace", "low_stimulation", "no_voice"], "mood_tags": ["calm"], "user_segment_tags": ["balanced_sleep", "environmental_sleep"], "quality_score": 0.84, "is_real": True, "voice_style": None},
    {"title": "格里格培尔金特组曲", "audio_type": "music", "request_text": "格里格培尔金特组曲晨景奥丝之死，温柔管弦轻音乐", "object_key": "real/music/22.mp3", "duration_sec": 897, "tags": ["ambient", "slow_pace", "low_stimulation", "no_voice"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["balanced_sleep", "companionship"], "quality_score": 0.82, "is_real": True, "voice_style": None},
    {"title": "舒伯特奏鸣曲D.959慢板", "audio_type": "music", "request_text": "舒伯特奏鸣曲行板回旋曲，绵长抒情钢琴独奏", "object_key": "real/music/23.mp3", "duration_sec": 1200, "tags": ["ambient", "minimal_voice", "slow_pace", "low_stimulation", "no_voice"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["balanced_sleep", "companionship"], "quality_score": 0.84, "is_real": True, "voice_style": None},
    {"title": "贝多芬第六弦乐四重奏", "audio_type": "music", "request_text": "贝多芬弦乐四重奏柔板乐章，舒缓弦乐合奏轻音乐", "object_key": "real/music/24.mp3", "duration_sec": 956, "tags": ["ambient", "slow_pace", "low_stimulation", "no_voice"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["balanced_sleep", "companionship"], "quality_score": 0.82, "is_real": True, "voice_style": None},
    {"title": "海顿云雀弦乐四重奏", "audio_type": "music", "request_text": "海顿云雀弦乐四重奏，柔美如歌的弦乐合奏轻音乐", "object_key": "real/music/25.mp3", "duration_sec": 890, "tags": ["ambient", "slow_pace", "low_stimulation", "no_voice"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["balanced_sleep", "companionship"], "quality_score": 0.82, "is_real": True, "voice_style": None},
    # =========================================================================
    # MEDITATION (6) — MiniMax TTS
    # =========================================================================
    {"title": "呼吸觉察·雨夜版", "audio_type": "meditation", "request_text": "温柔女声呼吸冥想配轻微雨声，焦虑舒缓，10分钟", "script_text": "现在，让我们开始今晚的呼吸练习。<#4#>轻轻闭上眼睛。<#5#>把注意力放到呼吸上。<#4#>吸气。<#5#>呼气。<#4#>不需要改变节奏。<#5#>只是注意到它。<#6#>吸气时，感受空气进入鼻腔的凉意。<#5#>呼气时，感受身体轻轻放松。<#6#>外面有轻柔的雨声。<#4#>每一滴雨都在帮你冲洗今天的疲惫。<#6#>继续呼吸。<#5#>吸气。<#6#>呼气。<#8#>你是安全的。<#10#>", "duration_sec": 600, "tags": ["breathing", "low_stimulation", "rain", "warm_voice", "slow_pace", "grounding", "short_duration", "minimal_voice"], "mood_tags": ["anxiety_relief", "calm"], "user_segment_tags": ["anxiety_relief", "quick_sleep"], "quality_score": 0.88, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "gentle_female"},
    {"title": "身体扫描放松", "audio_type": "meditation", "request_text": "引导式身体扫描冥想，从头到脚逐步放松，15分钟", "script_text": "欢迎来到今晚的放松练习。<#3#>找一个舒服的姿势躺好。<#5#>我们从头顶开始。<#4#>感受头皮慢慢放松。<#5#>眉头松开。<#4#>眼睛不再用力。<#5#>嘴角自然下垂。<#6#>脖子两侧的紧张感正在消散。<#5#>肩膀沉入枕头。<#6#>双臂变得温暖而沉重。<#5#>指尖微微发麻。<#6#>腹部随呼吸轻轻起伏。<#5#>髋部放松。<#5#>双腿彻底松软。<#6#>脚趾舒展。<#8#>整个身体都被温暖包裹着。<#10#>", "duration_sec": 900, "tags": ["grounding", "breathing", "slow_pace", "low_stimulation", "warm_voice"], "mood_tags": ["anxiety_relief", "calm"], "user_segment_tags": ["anxiety_relief", "balanced_sleep"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "gentle_female"},
    {"title": "正念当下·森林", "audio_type": "meditation", "request_text": "森林正念冥想，觉察当下，12分钟", "script_text": "此刻，你走进一片安静的森林。<#4#>脚下是柔软的落叶。<#5#>远处有鸟在轻声歌唱。<#4#>微风带来松木的气息。<#5#>你找到一棵大树，靠着它坐下。<#6#>闭上眼睛。<#5#>感受背后树干的温度。<#6#>你不需要去任何地方。<#5#>不需要做任何事。<#6#>只是在这里。<#5#>呼吸变得缓慢而深长。<#6#>森林接住了你所有的重量。<#8#>", "duration_sec": 720, "tags": ["nature", "breathing", "grounding", "slow_pace", "low_stimulation", "warm_voice"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["anxiety_relief", "companionship"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "whisper_female"},
    {"title": "入睡倒计时", "audio_type": "meditation", "request_text": "极简入睡引导，高密度停顿，8分钟快速入睡", "script_text": "十。<#6#>呼气。<#8#>九。<#6#>身体更沉。<#8#>八。<#7#>放松。<#9#>七。<#7#>不需要数。<#10#>六。<#8#>眼皮很重。<#10#>五。<#9#>快了。<#12#>四。<#10#>三。<#12#>二。<#15#>", "duration_sec": 480, "tags": ["slow_pace", "short_duration", "low_stimulation", "minimal_voice"], "mood_tags": ["calm"], "user_segment_tags": ["quick_sleep", "anxiety_relief"], "quality_score": 0.84, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "whisper_female"},
    {"title": "慈心冥想·温暖", "audio_type": "meditation", "request_text": "慈心冥想引导，给自己温暖和善意，15分钟", "script_text": "今晚，我们来做一个关于温暖的练习。<#4#>闭上眼睛。<#5#>想象心口有一团柔和的光。<#5#>它是温暖的。<#4#>现在，对自己说。<#5#>愿我平安。<#6#>愿我快乐。<#6#>愿我安睡。<#5#>感受这些话在心里回荡。<#6#>你值得被温柔对待。<#5#>你今天已经很努力了。<#6#>现在可以休息了。<#8#>光慢慢扩大，包裹住整个身体。<#10#>", "duration_sec": 900, "tags": ["warm_voice", "slow_pace", "low_stimulation", "grounding"], "mood_tags": ["safe", "gentle"], "user_segment_tags": ["companionship", "anxiety_relief"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "gentle_female"},
    {"title": "海边呼吸引导", "audio_type": "meditation", "request_text": "海边呼吸冥想引导，跟随海浪节奏呼吸，10分钟", "script_text": "想象你坐在一片安静的海边。<#4#>海浪轻轻涌来。<#5#>退去。<#5#>再涌来。<#6#>让呼吸跟随海浪的节奏。<#5#>海浪涌来时，吸气。<#6#>海浪退去时，呼气。<#6#>不需要用力。<#5#>海浪会带着你。<#6#>吸。<#7#>呼。<#7#>吸。<#8#>呼。<#9#>很好。<#10#>", "duration_sec": 600, "tags": ["breathing", "ocean", "low_stimulation", "warm_voice", "nature", "slow_pace"], "mood_tags": ["calm"], "user_segment_tags": ["anxiety_relief", "environmental_sleep"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "gentle_female"},
    # =========================================================================
    # STORY (4) + PODCAST_DIGEST (2) — MiniMax TTS
    # =========================================================================
    {"title": "海边书店的夜晚", "audio_type": "story", "request_text": "温柔女声讲海边书店的安静夜晚，15分钟", "script_text": "在一个安静的海边小镇，有一家旧书店。<#3#>傍晚时分，最后一个客人离开了。<#4#>店主没有关灯。<#5#>她喜欢在这种时候，独自坐在窗边。<#4#>远处的海浪声透过半开的窗户传进来。<#5#>书架上的书安静地排列着，像在等什么。<#4#>她随手翻开一本。<#5#>纸张的气味混合着海风。<#6#>故事里写着一个人在傍晚走进一家书店。<#5#>她笑了笑。<#4#>就像此刻。<#6#>暖黄的灯光落在书页上。<#5#>窗外的海浪声越来越轻。<#8#>她的眼皮慢慢合上。<#10#>", "duration_sec": 900, "tags": ["warm_voice", "gentle_story", "voice_present", "narrative", "slow_pace", "ocean"], "mood_tags": ["safe", "gentle"], "user_segment_tags": ["companionship", "balanced_sleep"], "quality_score": 0.87, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_female"},
    {"title": "猫与旧阁楼", "audio_type": "story", "request_text": "一只猫在旧阁楼发现秘密的温暖故事，12分钟", "script_text": "在城市的某个老房子里，有一个被遗忘的阁楼。<#3#>一只灰色的猫找到了通往那里的楼梯。<#4#>阁楼里很暗，但很温暖。<#5#>角落堆着旧箱子和发黄的报纸。<#4#>猫跳上一个木箱。<#5#>箱子里面有一条围巾，柔软而温暖。<#4#>猫把自己卷进去。<#6#>窗外传来远处的钟声。<#5#>阁楼里的灰尘在最后一缕光线中浮动。<#6#>猫闭上了眼睛。<#5#>这是它的秘密基地。<#8#>没有人知道。<#10#>", "duration_sec": 720, "tags": ["warm_voice", "gentle_story", "voice_present", "narrative", "slow_pace"], "mood_tags": ["gentle", "safe"], "user_segment_tags": ["companionship", "balanced_sleep"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_female"},
    {"title": "星空列车慢行记", "audio_type": "story", "request_text": "一列穿越星空的列车的奇幻睡前故事，20分钟", "script_text": "夜深了，站台上只剩你一个人。<#3#>一列没有编号的列车缓缓驶来。<#4#>车门打开，里面是暖黄色的灯光。<#5#>你走了进去。<#4#>列车开始移动，越来越快。<#5#>窗外的城市变成了星空。<#6#>你靠在柔软的座椅上。<#5#>车厢里很安静。<#4#>偶尔能听到轨道轻轻的咔哒声。<#6#>窗外的星星在缓缓流动。<#5#>列车没有目的地。<#6#>它只是在星星之间慢慢行驶。<#8#>你可以在任何时候睡着。<#10#>", "duration_sec": 1200, "tags": ["warm_voice", "gentle_story", "voice_present", "narrative", "slow_pace"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["companionship", "balanced_sleep"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "warm_female"},
    {"title": "雨夜城市漫步", "audio_type": "story", "request_text": "雨夜在安静城市散步的温柔叙事，15分钟", "script_text": "今晚下着小雨。<#3#>你撑着伞，走在安静的街上。<#4#>路灯把雨丝照得发亮。<#5#>地面倒映着暖色的光。<#4#>没有车。<#5#>没有行人。<#4#>只有你和雨声。<#6#>你经过一家面包店，虽然已经关门了。<#5#>空气里还有淡淡的烘焙香。<#6#>雨落在伞上的声音很轻很轻。<#5#>像有人在说：今天辛苦了。<#6#>你笑了笑，继续走着。<#8#>不着急回家。<#10#>", "duration_sec": 900, "tags": ["warm_voice", "gentle_story", "voice_present", "narrative", "slow_pace", "rain"], "mood_tags": ["calm"], "user_segment_tags": ["companionship", "environmental_sleep"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "warm_female"},
    {"title": "科技简报·助眠版", "audio_type": "podcast_digest", "request_text": "用平和声音讲几条科技短讯，低信息密度，10分钟", "script_text": "今天有几条轻松的科技消息。<#3#>科学家发现了一种能发光的蘑菇。<#4#>它们在深夜的森林里闪着淡绿色的光。<#5#>没人知道为什么，但很美。<#6#>另外，有人设计了一个帮助流浪猫找到家的小程序。<#5#>据说已经帮了一百多只猫。<#6#>嗯，其实这些也不急。<#5#>明天再想也来得及。<#8#>今晚先好好睡觉。<#10#>", "duration_sec": 600, "tags": ["voice_present", "narrative", "slow_pace", "low_stimulation"], "mood_tags": ["calm"], "user_segment_tags": ["content_transform", "balanced_sleep"], "quality_score": 0.82, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "podcast_male"},
    {"title": "历史小故事·古丝路", "audio_type": "podcast_digest", "request_text": "温柔讲述古丝绸之路的小故事，12分钟", "script_text": "很久以前，有一条连接东西方的路。<#3#>人们叫它丝绸之路。<#4#>不是真的铺满丝绸。<#5#>而是商人们带着丝绸、茶叶和瓷器，走过沙漠和山脉。<#6#>路很长。<#5#>有时候走几个月才到下一个城市。<#6#>但路上有驿站。<#5#>有水。<#4#>有同行的人。<#6#>他们在夜晚的篝火旁讲故事。<#5#>讲自己从哪里来。<#6#>讲要去哪里。<#8#>后来这些故事也跟着丝绸一起，到了很远的地方。<#10#>", "duration_sec": 720, "tags": ["voice_present", "narrative", "slow_pace", "low_stimulation"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["content_transform", "companionship"], "quality_score": 0.82, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_male"},
    # =========================================================================
    # EXPANSION 2026-07 — 32 条补充内容（Hermes 匹配导向）
    # 无 script_text：由 prewarm 管线的 DirectivePlanner + LLM 现场撰写脚本
    # =========================================================================
    # --- MEDITATION +8 ---
    {"title": "4-7-8呼吸法", "audio_type": "meditation", "request_text": "4-7-8呼吸法入睡引导，吸气4秒屏息7秒呼气8秒，温柔女声，8分钟", "duration_sec": 480, "tags": ["breathing", "quick_sleep", "low_stimulation", "warm_voice", "short_duration"], "mood_tags": ["anxiety_relief", "calm"], "user_segment_tags": ["quick_sleep", "anxiety_relief"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "gentle_female"},
    {"title": "渐进肌肉放松", "audio_type": "meditation", "request_text": "渐进式肌肉放松练习，逐个部位收紧再放松，缓解紧绷，15分钟", "duration_sec": 900, "tags": ["grounding", "slow_pace", "low_stimulation", "warm_voice"], "mood_tags": ["anxiety_relief", "calm"], "user_segment_tags": ["anxiety_relief", "balanced_sleep"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "gentle_female"},
    {"title": "星空躺卧冥想", "audio_type": "meditation", "request_text": "躺在草地上仰望星空的冥想引导，星星缓缓流动，12分钟", "duration_sec": 720, "tags": ["stars", "nature", "grounding", "slow_pace", "low_stimulation"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["companionship", "balanced_sleep"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "whisper_female"},
    {"title": "雨夜窗边冥想", "audio_type": "meditation", "request_text": "雨夜坐在窗边听雨的冥想引导，雨声意象放松身心，10分钟", "duration_sec": 600, "tags": ["rain", "breathing", "grounding", "warm_voice", "slow_pace"], "mood_tags": ["calm", "anxiety_relief"], "user_segment_tags": ["environmental_sleep", "anxiety_relief"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "gentle_female"},
    {"title": "温泉暖流放松", "audio_type": "meditation", "request_text": "想象泡在温泉里暖流包裹身体的放松引导，温暖意象，12分钟", "duration_sec": 720, "tags": ["grounding", "warm_voice", "slow_pace", "low_stimulation"], "mood_tags": ["safe", "gentle"], "user_segment_tags": ["anxiety_relief", "companionship"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "gentle_female"},
    {"title": "月光森林散步", "audio_type": "meditation", "request_text": "月光下的森林散步引导冥想，夜晚森林意象，12分钟", "duration_sec": 720, "tags": ["nature", "forest", "grounding", "slow_pace", "low_stimulation"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["companionship", "balanced_sleep"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "whisper_female"},
    {"title": "晚安感谢练习", "audio_type": "meditation", "request_text": "睡前感谢身体的温柔练习，感谢今天的自己，10分钟", "duration_sec": 600, "tags": ["warm_voice", "grounding", "slow_pace", "low_stimulation"], "mood_tags": ["gentle", "safe"], "user_segment_tags": ["companionship", "anxiety_relief"], "quality_score": 0.84, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "gentle_female"},
    {"title": "深呼吸快睡", "audio_type": "meditation", "request_text": "极简深呼吸快速入睡引导，长停顿少语言，8分钟", "duration_sec": 480, "tags": ["breathing", "quick_sleep", "minimal_voice", "short_duration", "low_stimulation"], "mood_tags": ["calm"], "user_segment_tags": ["quick_sleep"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "whisper_female"},
    # --- STORY +12 ---
    {"title": "萤火虫谷", "audio_type": "story", "request_text": "夏夜山谷里萤火虫飞舞的治愈睡前故事，温柔女声，12分钟", "duration_sec": 720, "tags": ["gentle_story", "nature", "warm_voice", "narrative", "slow_pace"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["companionship", "balanced_sleep"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_female"},
    {"title": "蜗牛慢递邮局", "audio_type": "story", "request_text": "森林里蜗牛开慢递邮局的温暖童话，慢节奏，12分钟", "duration_sec": 720, "tags": ["gentle_story", "nature", "warm_voice", "narrative", "slow_pace"], "mood_tags": ["gentle", "safe"], "user_segment_tags": ["companionship"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_female"},
    {"title": "云朵牧场", "audio_type": "story", "request_text": "天空中牧羊人放牧云朵的奇幻温柔故事，15分钟", "duration_sec": 900, "tags": ["gentle_story", "narrative", "warm_voice", "slow_pace"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["companionship", "balanced_sleep"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_female"},
    {"title": "深夜面包房", "audio_type": "story", "request_text": "深夜面包房里烤面包香气的温暖日常故事，12分钟", "duration_sec": 720, "tags": ["gentle_story", "warm_voice", "narrative", "slow_pace"], "mood_tags": ["safe", "gentle"], "user_segment_tags": ["companionship", "balanced_sleep"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "warm_female"},
    {"title": "旧书店的猫", "audio_type": "story", "request_text": "旧书店里一只猫守着书架打盹的安静故事，12分钟", "duration_sec": 720, "tags": ["gentle_story", "warm_voice", "narrative", "slow_pace"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["companionship"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_female"},
    {"title": "末班电车", "audio_type": "story", "request_text": "深夜末班电车缓缓驶过城市的温柔叙事故事，15分钟", "duration_sec": 900, "tags": ["gentle_story", "narrative", "slow_pace", "warm_voice"], "mood_tags": ["calm"], "user_segment_tags": ["balanced_sleep", "companionship"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "warm_female"},
    {"title": "月亮图书馆", "audio_type": "story", "request_text": "月亮上一座安静图书馆的奇幻睡前故事，月球借书人，15分钟", "duration_sec": 900, "tags": ["gentle_story", "stars", "narrative", "warm_voice", "slow_pace"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["companionship", "balanced_sleep"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_female"},
    {"title": "海底邮差", "audio_type": "story", "request_text": "海底世界送信的邮差鱼的奇幻温柔故事，12分钟", "duration_sec": 720, "tags": ["gentle_story", "ocean", "narrative", "slow_pace"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["companionship"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_female"},
    {"title": "风的收藏家", "audio_type": "story", "request_text": "收集世界各地的风装进玻璃瓶的奇幻故事，15分钟", "duration_sec": 900, "tags": ["gentle_story", "narrative", "warm_voice", "slow_pace"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["companionship", "balanced_sleep"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "warm_female"},
    {"title": "迷路的小鹿", "audio_type": "story", "request_text": "一只小鹿在深山里迷了路，跟着萤火和溪流找到回家路的睡前童话，12分钟", "duration_sec": 720, "tags": ["gentle_story", "nature", "forest", "narrative", "warm_voice"], "mood_tags": ["gentle", "safe"], "user_segment_tags": ["companionship"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_female"},
    {"title": "冬眠前的熊", "audio_type": "story", "request_text": "秋天结束时小熊收拾树洞准备冬眠、和朋友们道晚安的温暖童话，12分钟", "duration_sec": 720, "tags": ["gentle_story", "nature", "narrative", "warm_voice", "slow_pace"], "mood_tags": ["safe", "gentle"], "user_segment_tags": ["companionship"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_male"},
    {"title": "灯塔猫头鹰", "audio_type": "story", "request_text": "海边灯塔上猫头鹰守夜的安静故事，15分钟", "duration_sec": 900, "tags": ["gentle_story", "ocean", "narrative", "slow_pace"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["companionship", "balanced_sleep"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_male"},
    # --- ASMR +6 ---
    {"title": "耳边晚安絮语", "audio_type": "asmr", "request_text": "耳边轻声说晚安的asmr低语，轻柔耳语，10分钟", "duration_sec": 600, "tags": ["whisper", "minimal_voice", "low_stimulation", "slow_pace"], "mood_tags": ["gentle", "safe"], "user_segment_tags": ["companionship", "quick_sleep"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "whisper_female"},
    {"title": "雨声伴读", "audio_type": "asmr", "request_text": "雨声背景下轻声念散文的asmr伴读，12分钟", "duration_sec": 720, "tags": ["whisper", "rain", "minimal_voice", "low_stimulation"], "mood_tags": ["calm"], "user_segment_tags": ["environmental_sleep", "companionship"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "whisper_female"},
    {"title": "翻书与低语", "audio_type": "asmr", "request_text": "轻轻翻书页伴随低语的asmr，安静书房氛围，10分钟", "duration_sec": 600, "tags": ["whisper", "minimal_voice", "low_stimulation", "slow_pace"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["companionship"], "quality_score": 0.84, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "whisper_female"},
    {"title": "篝火旁的耳语", "audio_type": "asmr", "request_text": "篝火旁轻声讲话的asmr耳语，温暖火堆氛围，12分钟", "duration_sec": 720, "tags": ["whisper", "fire", "minimal_voice", "low_stimulation"], "mood_tags": ["safe", "gentle"], "user_segment_tags": ["companionship", "environmental_sleep"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "whisper_female"},
    {"title": "轻声数星星", "audio_type": "asmr", "request_text": "躺着轻声数星星哄睡的asmr低语，10分钟", "duration_sec": 600, "tags": ["whisper", "stars", "minimal_voice", "quick_sleep"], "mood_tags": ["gentle", "calm"], "user_segment_tags": ["quick_sleep", "companionship"], "quality_score": 0.84, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "whisper_female"},
    {"title": "睡前轻声诗", "audio_type": "asmr", "request_text": "轻声念温柔短诗的asmr，缓慢柔和，8分钟", "duration_sec": 480, "tags": ["whisper", "minimal_voice", "short_duration", "slow_pace"], "mood_tags": ["gentle"], "user_segment_tags": ["companionship"], "quality_score": 0.84, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "whisper_female"},
    # --- PODCAST_DIGEST +6 ---
    {"title": "宇宙冷知识夜读", "audio_type": "podcast_digest", "request_text": "用平静声音讲宇宙冷知识的助眠夜读播客，12分钟", "duration_sec": 720, "tags": ["voice_present", "narrative", "stars", "slow_pace", "low_stimulation"], "mood_tags": ["calm"], "user_segment_tags": ["content_transform", "balanced_sleep"], "quality_score": 0.84, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "podcast_male"},
    {"title": "深海生物夜话", "audio_type": "podcast_digest", "request_text": "轻声介绍深海奇妙生物的助眠播客，12分钟", "duration_sec": 720, "tags": ["voice_present", "narrative", "ocean", "slow_pace", "low_stimulation"], "mood_tags": ["calm"], "user_segment_tags": ["content_transform", "balanced_sleep"], "quality_score": 0.84, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "podcast_male"},
    {"title": "温和幽默夜谈", "audio_type": "podcast_digest", "request_text": "轻松温和的脱口秀式夜谈，讲生活里的小趣事，不吵闹适合睡前，12分钟", "duration_sec": 720, "tags": ["voice_present", "narrative", "slow_pace", "humor"], "mood_tags": ["gentle", "calm"], "user_segment_tags": ["companionship", "content_transform"], "quality_score": 0.84, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_male"},
    {"title": "生活小事夜谈", "audio_type": "podcast_digest", "request_text": "聊便利店关东煮和楼下猫咪的轻松夜谈播客，10分钟", "duration_sec": 600, "tags": ["voice_present", "narrative", "slow_pace", "humor"], "mood_tags": ["gentle"], "user_segment_tags": ["companionship"], "quality_score": 0.83, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "warm_female"},
    {"title": "名画背后的夜晚", "audio_type": "podcast_digest", "request_text": "轻声讲名画背后小故事的艺术夜读，10分钟", "duration_sec": 600, "tags": ["voice_present", "narrative", "slow_pace", "low_stimulation"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["content_transform"], "quality_score": 0.83, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "warm_female"},
    {"title": "老街巷的旧时光", "audio_type": "podcast_digest", "request_text": "讲老街巷弄旧时光的怀旧夜话，温和男声，12分钟", "duration_sec": 720, "tags": ["voice_present", "narrative", "slow_pace", "low_stimulation"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["companionship", "content_transform"], "quality_score": 0.83, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_male"},
]
